AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        ENVIRONMENT: "dev"
        LOGGING_LEVEL: "debug"
        LOGGING_DRIVER: "console"
        TWILIO_ACCOUNT_SID: "ACd74a362180af1e54e63db8cce61ccb67"
        TWILIO_AUTH_TOKEN: "91c1cb2790e0123ca55d360073682499"

Resources:
  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: postconfirmation-lda
      CodeUri: postconfirmation/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: presignup-lda
      CodeUri: presignup/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
