AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >


Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        ENVIRONMENT: "dev"
        LOGGING_LEVEL: "debug"
        LOGGING_DRIVER: "console"
        DYNAMODB_TABLE_NAME: "users"
        COGNITO_USERPOOL_ID: "ap-southeast-2_YmaroG5KO"

Resources:
  UserServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: users-service-lda
      CodeUri: users-service/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
